name: "Chromatic"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        yarn && git status --porcelain
    - uses: chromaui/action@v1
      with: 
        appCode: ${{ secrets.CHROMATIC_APP_CODE }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: tests
      - run:
          command: npm lint # lint your code
      - run:
          command: npm test # run your unit tests
      - run:
          command: npm run chromatic # run your visual tests