name: "Chromatic"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        yarn && git status --porcelain
        yarn chromatic
    - uses: chromaui/action@v1
      with: 
        appCode: ${{ secrets.CHROMATIC_APP_CODE }}
        token: ${{ secrets.GITHUB_TOKEN }}