name: "Chromatic"

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: chromaui/action@v1
      with: 
        appCode: i67m81xuk4p
        token: ${{ secrets.GITHUB_TOKEN }}
